version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: ingredients_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ""
    volumes:
      - neo4j_data:/data
    networks:
      - ingredients_network

  aspnetapp:
    build: ./
    container_name: ingredients_aspnet
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - NEO4J_URI=bolt://neo4j:7687
    depends_on:
      - neo4j
    networks:
      - ingredients_network

networks:
  ingredients_network:
    driver: bridge

volumes:
  neo4j_data:
    driver: local